@url = http://localhost:5000/api

###

GET {{url}}/user

### 

POST {{url}}/user 
content-type: application/json

{
  "username": "测试4号",
  "password": "123456"
}

### 

DELETE {{url}}/user?id=6
content-type: application/json