@url = http://localhost:5000/api/user

###

GET {{url}}/list

### 

GET {{url}}?id=8
content-type: application/json

### 

POST {{url}}/register 
content-type: application/json

{
  "username": "测试7号",
  "password": "123456"
}

### 

DELETE {{url}}?id=7
content-type: application/json